name: cdi_workshop
channels:
  - conda-forge
dependencies:
  - python
  - pydensecrf
  - cython
  - numpy
  - scipy
  - matplotlib
  - scikit-image
  - scikit-learn
  - joblib
  - tensorflow
  - opencv
  - ipython
  - tensorflow-hub
  - jupyter
  - tqdm
  - s3fs
  - gdal
  - rasterio
  - pyviz/label/earthsim::holoviews=1.11.0a6
  - pyviz/label/earthsim::panel=0.1.0a14
  - imageio
  - ipywidgets
  - pyviz/label/earthsim::bokeh=1.0.0dev5